import type { Prompt } from '@/types';

export const mockPrompts: Prompt[] = [
  {
    id: 'p1',
    title: 'React Component Generator',
    description: 'Generates production-ready React components with TypeScript, props interface, and Tailwind styling.',
    content: 'You are a senior React developer. Generate a production-ready React component based on the following specification. Use TypeScript with explicit prop types, Tailwind CSS for styling, and include proper accessibility attributes. The component should be self-contained and export a default function. Include JSDoc comments for complex logic.',
    category: 'Coding',
    models: ['Claude', 'GPT-4', 'GPT-4o'],
    bestModel: 'Claude',
    tags: ['react', 'typescript', 'frontend', 'components'],
    effectiveness: 5,
    qualityTag: 'great',
    usageCount: 142,
    project: 'E-commerce Platform',
    isFavorite: true,
    createdAt: '2024-08-15T10:00:00Z',
    updatedAt: '2025-01-20T14:30:00Z',
    improvements: ['Consider adding error boundary patterns', 'Include unit test scaffolding in output'],
    versions: [
      { id: 'v1-1', version: 1, content: 'Generate a React component with TypeScript and Tailwind.', createdAt: '2024-08-15T10:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v1-2', version: 2, content: 'You are a React developer. Generate a component with TypeScript, Tailwind CSS, and accessibility attributes.', createdAt: '2024-10-05T09:00:00Z', rating: 4, qualityTag: 'great' },
      { id: 'v1-3', version: 3, content: 'You are a senior React developer. Generate a production-ready React component based on the following specification. Use TypeScript with explicit prop types, Tailwind CSS for styling, and include proper accessibility attributes. The component should be self-contained and export a default function. Include JSDoc comments for complex logic.', createdAt: '2025-01-20T14:30:00Z', rating: 5, qualityTag: 'great' },
    ],
  },
  {
    id: 'p2',
    title: 'SQL Query Optimizer',
    description: 'Analyzes and rewrites SQL queries for better performance with index suggestions.',
    content: 'Act as a database performance engineer. Analyze the provided SQL query and rewrite it for optimal performance. Explain each optimization step, suggest useful indexes, identify potential N+1 query patterns, and provide the estimated performance improvement. Format your response with: Original Analysis, Optimized Query, Index Recommendations, Performance Notes.',
    category: 'Coding',
    models: ['GPT-4', 'Claude'],
    bestModel: 'GPT-4',
    tags: ['sql', 'database', 'performance', 'optimization'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 87,
    project: 'Data Pipeline',
    isFavorite: true,
    createdAt: '2024-07-22T08:00:00Z',
    updatedAt: '2025-01-05T11:00:00Z',
    improvements: ['Add specific DBMS context (PostgreSQL/MySQL)', 'Include query plan analysis instructions'],
    versions: [
      { id: 'v2-1', version: 1, content: 'Optimize this SQL query for better performance.', createdAt: '2024-07-22T08:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v2-2', version: 2, content: 'Act as a database performance engineer. Analyze the provided SQL query and rewrite it for optimal performance. Explain each optimization step, suggest useful indexes, identify potential N+1 query patterns, and provide the estimated performance improvement.', createdAt: '2025-01-05T11:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p3',
    title: 'Long-Form Blog Writer',
    description: 'Creates SEO-optimized, engaging blog posts with proper structure and tone.',
    content: 'You are an experienced content strategist and writer. Write a comprehensive blog post on the given topic. Structure: compelling headline, hook introduction (2-3 sentences), 4-6 sections with H2 subheadings, actionable takeaways, and a conclusion with CTA. Tone should be authoritative yet conversational. Include relevant statistics or examples where appropriate. Target word count: 1500-2000 words. Optimize for the target keyword naturally—avoid keyword stuffing.',
    category: 'Writing',
    models: ['Claude', 'GPT-4o'],
    bestModel: 'Claude',
    tags: ['blog', 'seo', 'content-marketing', 'writing'],
    effectiveness: 5,
    qualityTag: 'great',
    usageCount: 203,
    project: 'Blog Engine',
    isFavorite: true,
    createdAt: '2024-06-10T12:00:00Z',
    updatedAt: '2025-02-01T09:00:00Z',
    improvements: ['Add audience persona specification', 'Include internal linking strategy guidance'],
    versions: [
      { id: 'v3-1', version: 1, content: 'Write a blog post about the given topic.', createdAt: '2024-06-10T12:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v3-2', version: 2, content: 'Write a comprehensive blog post with proper SEO structure, engaging tone, and actionable takeaways.', createdAt: '2024-09-15T10:00:00Z', rating: 4, qualityTag: 'great' },
      { id: 'v3-3', version: 3, content: 'You are an experienced content strategist and writer. Write a comprehensive blog post on the given topic. Structure: compelling headline, hook introduction, 4-6 sections with H2 subheadings, actionable takeaways, and a conclusion with CTA. Target word count: 1500-2000 words.', createdAt: '2025-02-01T09:00:00Z', rating: 5, qualityTag: 'great' },
    ],
  },
  {
    id: 'p4',
    title: 'Market Analysis Report',
    description: 'Produces structured competitive market analysis with data-driven insights.',
    content: 'You are a market research analyst at a top consulting firm. Create a detailed market analysis report for the specified industry or product segment. Include: Executive Summary, Market Size & Growth Trends, Key Players & Market Share, SWOT Analysis, Consumer Behavior Insights, Emerging Trends & Opportunities, Risk Factors, and Strategic Recommendations. Use data-driven language and cite plausible market figures. Present findings in a professional report format.',
    category: 'Analysis',
    models: ['Gemini Pro', 'GPT-4', 'Claude'],
    bestModel: 'Gemini Pro',
    tags: ['market-research', 'competitive-analysis', 'business', 'strategy'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 64,
    project: undefined,
    isFavorite: false,
    createdAt: '2024-09-01T15:00:00Z',
    updatedAt: '2024-12-20T16:00:00Z',
    improvements: ['Specify geographic market scope', 'Add time horizon for projections', 'Include data visualization requests'],
    versions: [
      { id: 'v4-1', version: 1, content: 'Create a market analysis for the given industry.', createdAt: '2024-09-01T15:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v4-2', version: 2, content: 'You are a market research analyst. Create a detailed market analysis report including SWOT analysis, key players, and strategic recommendations.', createdAt: '2024-12-20T16:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p5',
    title: 'Creative Brainstorming Engine',
    description: 'Generates diverse creative ideas using lateral thinking techniques.',
    content: 'You are a creative director at an innovation lab. Use lateral thinking, SCAMPER method, and random association techniques to brainstorm ideas for the given challenge. Generate exactly 10 ideas ranging from practical to wildly unconventional. For each idea provide: a catchy name, one-sentence pitch, feasibility score (1-5), and novelty score (1-5). End with your top 3 recommendations and why they stand out. Think beyond obvious solutions.',
    category: 'Brainstorming',
    models: ['GPT-4o', 'Claude', 'Gemini Pro'],
    bestModel: 'GPT-4o',
    tags: ['ideation', 'creativity', 'innovation', 'brainstorming'],
    effectiveness: 3,
    qualityTag: 'okay',
    usageCount: 45,
    project: undefined,
    isFavorite: false,
    createdAt: '2024-10-12T08:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    improvements: ['Add constraint parameters for budget/timeline', 'Specify industry vertical', 'Include implementation roadmap for top picks'],
    versions: [
      { id: 'v5-1', version: 1, content: 'Brainstorm 10 creative ideas for the given challenge.', createdAt: '2024-10-12T08:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v5-2', version: 2, content: 'Use SCAMPER and lateral thinking to brainstorm 10 ideas. For each, provide a name, pitch, feasibility and novelty scores.', createdAt: '2025-01-15T10:00:00Z', rating: 3, qualityTag: 'okay' },
    ],
  },
  {
    id: 'p6',
    title: 'CSV Data Parser & Cleaner',
    description: 'Extracts, cleans, and transforms messy CSV data into structured formats.',
    content: 'You are a data engineer specializing in ETL pipelines. Parse the provided CSV data and perform the following: 1) Identify and report data quality issues (missing values, inconsistent formats, duplicates, outliers). 2) Clean the data by standardizing formats, handling nulls with appropriate strategies, and removing exact duplicates. 3) Output the cleaned data as a properly formatted CSV. 4) Provide a data quality report summarizing changes made. Use Python pandas syntax for any transformations described.',
    category: 'Data Extraction',
    models: ['Claude', 'GPT-4'],
    bestModel: 'Claude',
    tags: ['csv', 'data-cleaning', 'etl', 'python'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 56,
    project: 'Data Pipeline',
    isFavorite: false,
    createdAt: '2024-08-20T14:00:00Z',
    updatedAt: '2024-11-30T12:00:00Z',
    improvements: ['Add schema validation rules', 'Include data profiling statistics'],
    versions: [
      { id: 'v6-1', version: 1, content: 'Clean this CSV data and fix any issues.', createdAt: '2024-08-20T14:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v6-2', version: 2, content: 'Parse the CSV, identify quality issues, clean the data, and provide a quality report. Use pandas syntax.', createdAt: '2024-11-30T12:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p7',
    title: 'DALL-E Prompt Crafter',
    description: 'Transforms simple descriptions into detailed, effective image generation prompts.',
    content: 'You are an expert prompt engineer for AI image generation models (DALL-E, Midjourney, Stable Diffusion). Transform the user\'s simple description into a detailed, effective image generation prompt. Include: subject description with specific details, art style reference, lighting and mood, camera angle/composition, color palette, and quality modifiers. Provide 3 variations: photorealistic, artistic/painterly, and stylized/graphic. Each should be 40-80 words. Avoid banned terms and ensure the prompts are model-safe.',
    category: 'Image Generation',
    models: ['GPT-4', 'GPT-4o', 'Claude'],
    bestModel: 'GPT-4',
    tags: ['dall-e', 'midjourney', 'image-gen', 'creative'],
    effectiveness: 5,
    qualityTag: 'great',
    usageCount: 178,
    project: undefined,
    isFavorite: true,
    createdAt: '2024-05-08T09:00:00Z',
    updatedAt: '2025-01-28T17:00:00Z',
    improvements: ['Add negative prompt suggestions', 'Include aspect ratio recommendations per platform'],
    versions: [
      { id: 'v7-1', version: 1, content: 'Create a DALL-E prompt for this description.', createdAt: '2024-05-08T09:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v7-2', version: 2, content: 'Transform the description into a detailed image prompt with art style, lighting, composition, and quality modifiers.', createdAt: '2024-09-22T11:00:00Z', rating: 4, qualityTag: 'great' },
      { id: 'v7-3', version: 3, content: 'You are an expert prompt engineer for AI image generation. Provide 3 variations: photorealistic, artistic, and stylized. Each 40-80 words with subject, style, lighting, composition, and color details.', createdAt: '2025-01-28T17:00:00Z', rating: 5, qualityTag: 'great' },
    ],
  },
  {
    id: 'p8',
    title: 'Technical Document Translator',
    description: 'Translates technical documentation while preserving domain-specific terminology.',
    content: 'You are a professional technical translator. Translate the following technical document from [SOURCE] to [TARGET] language. Preserve all technical terminology, code snippets, variable names, and API references exactly as-is. Maintain the original formatting structure (headings, lists, code blocks). For domain-specific terms with no direct translation, keep the English term with a parenthetical translation on first occurrence. Flag any ambiguous passages that may need human review.',
    category: 'Translation',
    models: ['Gemini Pro', 'GPT-4', 'Claude'],
    bestModel: 'Gemini Pro',
    tags: ['translation', 'documentation', 'technical-writing', 'localization'],
    effectiveness: 3,
    qualityTag: 'okay',
    usageCount: 31,
    project: undefined,
    isFavorite: false,
    createdAt: '2024-11-05T10:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
    improvements: ['Specify source/target language pairs upfront', 'Add glossary attachment support', 'Include back-translation verification step'],
    versions: [
      { id: 'v8-1', version: 1, content: 'Translate this technical document to the target language.', createdAt: '2024-11-05T10:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v8-2', version: 2, content: 'Translate preserving technical terms, code snippets, and formatting. Flag ambiguous passages.', createdAt: '2025-01-10T08:00:00Z', rating: 3, qualityTag: 'okay' },
    ],
  },
  {
    id: 'p9',
    title: 'Python Debugger Assistant',
    description: 'Diagnoses Python bugs with root cause analysis and fix recommendations.',
    content: 'You are a senior Python developer debugging production code. Analyze the provided Python code and error traceback. Provide: 1) Root Cause Analysis — explain exactly why the error occurs. 2) The Fix — provide corrected code with minimal changes highlighted. 3) Prevention — suggest how to prevent this class of bug (e.g., type hints, assertions, tests). 4) Related Pitfalls — mention 2-3 similar bugs that commonly occur in this pattern. Keep explanations concise and code-focused.',
    category: 'Debugging',
    models: ['Claude', 'GPT-4o'],
    bestModel: 'Claude',
    tags: ['python', 'debugging', 'error-handling', 'code-review'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 93,
    project: 'Data Pipeline',
    isFavorite: true,
    createdAt: '2024-07-01T11:00:00Z',
    updatedAt: '2025-01-25T13:00:00Z',
    improvements: ['Add Python version context', 'Include performance profiling tips when relevant'],
    versions: [
      { id: 'v9-1', version: 1, content: 'Debug this Python code and fix the error.', createdAt: '2024-07-01T11:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v9-2', version: 2, content: 'Analyze the code and traceback. Provide root cause, fix, prevention strategy, and related pitfalls.', createdAt: '2025-01-25T13:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p10',
    title: 'Research Paper Summarizer',
    description: 'Distills academic papers into structured, actionable summaries.',
    content: 'You are a research scientist. Summarize the provided academic paper using this structure: 1) One-Line Summary (tweet-length). 2) Key Contribution — what\'s new and why it matters. 3) Methodology — approach and experimental setup in plain language. 4) Main Results — quantitative findings with specific numbers. 5) Limitations — what the authors acknowledge or miss. 6) Practical Implications — how this affects practitioners. 7) Related Work — 3 papers to read next. Avoid jargon where possible; define specialized terms on first use.',
    category: 'Research',
    models: ['Claude', 'GPT-4o', 'Gemini Pro'],
    bestModel: 'Claude',
    tags: ['academic', 'research', 'summarization', 'papers'],
    effectiveness: 5,
    qualityTag: 'great',
    usageCount: 116,
    project: undefined,
    isFavorite: true,
    createdAt: '2024-06-25T16:00:00Z',
    updatedAt: '2025-02-05T10:00:00Z',
    improvements: ['Add citation format preference (APA/MLA)', 'Include visual/figure descriptions'],
    versions: [
      { id: 'v10-1', version: 1, content: 'Summarize this research paper.', createdAt: '2024-06-25T16:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v10-2', version: 2, content: 'Summarize using structured sections: key contribution, methodology, results, limitations, and implications.', createdAt: '2024-10-15T14:00:00Z', rating: 4, qualityTag: 'great' },
      { id: 'v10-3', version: 3, content: 'Full structured summary with one-line summary, key contribution, methodology, results, limitations, practical implications, and related work. Avoid jargon.', createdAt: '2025-02-05T10:00:00Z', rating: 5, qualityTag: 'great' },
    ],
  },
  {
    id: 'p11',
    title: 'API Documentation Writer',
    description: 'Generates comprehensive REST API documentation from endpoint specs.',
    content: 'You are a technical writer specializing in API documentation. Generate comprehensive documentation for the provided API endpoint(s). For each endpoint include: HTTP method and path, description, authentication requirements, request parameters (path, query, body) with types and constraints, example request with cURL and JavaScript fetch, response schema with all fields described, status codes and error responses, and rate limiting notes. Use OpenAPI-style formatting. Include realistic example data.',
    category: 'Writing',
    models: ['Claude', 'GPT-4'],
    bestModel: 'Claude',
    tags: ['api', 'documentation', 'rest', 'technical-writing'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 72,
    project: 'E-commerce Platform',
    isFavorite: false,
    createdAt: '2024-09-15T09:00:00Z',
    updatedAt: '2024-12-10T15:00:00Z',
    improvements: ['Add GraphQL support option', 'Include SDK code samples in multiple languages'],
    versions: [
      { id: 'v11-1', version: 1, content: 'Write API documentation for this endpoint.', createdAt: '2024-09-15T09:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v11-2', version: 2, content: 'Generate comprehensive API docs with method, params, request/response examples, status codes, and rate limits.', createdAt: '2024-12-10T15:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p12',
    title: 'Competitive SWOT Analyzer',
    description: 'Performs structured competitive analysis with actionable strategic insights.',
    content: 'Analyze the competitive landscape for [COMPANY/PRODUCT]. Produce a structured SWOT analysis with at least 4 points per quadrant. Include: market positioning map, key differentiators vs top 3 competitors, pricing strategy analysis, and 3 actionable strategic recommendations with expected impact and effort scores. Format as a presentation-ready report with clear headings.',
    category: 'Analysis',
    models: ['Gemini Pro', 'GPT-4'],
    bestModel: 'Gemini Pro',
    tags: ['competitive-analysis', 'swot', 'strategy', 'business'],
    effectiveness: 3,
    qualityTag: 'okay',
    usageCount: 38,
    project: undefined,
    isFavorite: false,
    createdAt: '2024-10-20T14:00:00Z',
    updatedAt: '2024-12-28T11:00:00Z',
    improvements: ['Specify industry context', 'Add time-bound trend analysis', 'Include customer sentiment data angle'],
    versions: [
      { id: 'v12-1', version: 1, content: 'Do a SWOT analysis for this company.', createdAt: '2024-10-20T14:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v12-2', version: 2, content: 'Full SWOT with 4+ points per quadrant, competitor comparison, pricing analysis, and strategic recommendations.', createdAt: '2024-12-28T11:00:00Z', rating: 3, qualityTag: 'okay' },
    ],
  },
  {
    id: 'p13',
    title: 'UI/UX Design Ideation',
    description: 'Generates design concepts with wireframe descriptions and interaction patterns.',
    content: 'You are a senior product designer. For the given feature or screen, generate 3 distinct design concepts. For each concept provide: 1) Design Philosophy (1 sentence). 2) Layout Description — wireframe-level detail of component placement. 3) Key Interaction Patterns — animations, transitions, gestures. 4) Accessibility Considerations. 5) Technical Feasibility notes. Compare the 3 concepts and recommend one with justification. Reference real-world apps as inspiration where relevant.',
    category: 'Brainstorming',
    models: ['GPT-4o', 'Claude'],
    bestModel: 'GPT-4o',
    tags: ['ui', 'ux', 'design', 'wireframe', 'product'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 59,
    project: 'Mobile App',
    isFavorite: false,
    createdAt: '2024-08-08T13:00:00Z',
    updatedAt: '2025-01-12T16:00:00Z',
    improvements: ['Add platform-specific guidelines (iOS HIG / Material Design)', 'Include user flow diagram descriptions'],
    versions: [
      { id: 'v13-1', version: 1, content: 'Design 3 UI concepts for this feature.', createdAt: '2024-08-08T13:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v13-2', version: 2, content: 'Generate 3 design concepts with layout, interactions, accessibility, and feasibility. Compare and recommend one.', createdAt: '2025-01-12T16:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p14',
    title: 'JSON Schema Extractor',
    description: 'Infers and generates JSON Schema from sample data with validation rules.',
    content: 'Analyze the provided JSON data sample(s) and generate a comprehensive JSON Schema (draft-07). Include: all property types with descriptions, required vs optional fields, format validators (email, uri, date-time, etc.), enum constraints where values are clearly bounded, pattern validators for strings with consistent formats, array item schemas with minItems/maxItems, and nested object schemas. Provide the schema plus 2 example payloads—one valid, one invalid with expected validation errors.',
    category: 'Data Extraction',
    models: ['Claude', 'GPT-4'],
    bestModel: 'Claude',
    tags: ['json', 'schema', 'validation', 'data-modeling'],
    effectiveness: 5,
    qualityTag: 'great',
    usageCount: 84,
    project: 'Data Pipeline',
    isFavorite: true,
    createdAt: '2024-07-18T10:00:00Z',
    updatedAt: '2025-01-30T09:00:00Z',
    improvements: ['Support OpenAPI 3.0 schema format option', 'Add migration path from older schema drafts'],
    versions: [
      { id: 'v14-1', version: 1, content: 'Generate a JSON Schema from this data.', createdAt: '2024-07-18T10:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v14-2', version: 2, content: 'Generate JSON Schema draft-07 with types, formats, enums, patterns, and examples.', createdAt: '2024-11-10T08:00:00Z', rating: 4, qualityTag: 'great' },
      { id: 'v14-3', version: 3, content: 'Full JSON Schema with descriptions, validators, nested schemas, plus valid and invalid example payloads.', createdAt: '2025-01-30T09:00:00Z', rating: 5, qualityTag: 'great' },
    ],
  },
  {
    id: 'p15',
    title: 'Midjourney Prompt Builder',
    description: 'Creates optimized Midjourney prompts with parameter tuning.',
    content: 'You are a Midjourney prompt expert. Convert the user\'s concept into an optimized Midjourney prompt. Include: detailed subject description, environment/setting, artistic style or artist references, lighting and atmosphere, and recommended Midjourney parameters (--ar, --v, --style, --chaos, --stylize). Provide 3 prompt variations at different stylize levels (low/medium/high). Add negative prompts using --no parameter for common artifacts to avoid.',
    category: 'Image Generation',
    models: ['GPT-4', 'Claude'],
    bestModel: 'GPT-4',
    tags: ['midjourney', 'image-gen', 'creative', 'ai-art'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 134,
    project: undefined,
    isFavorite: false,
    createdAt: '2024-06-15T11:00:00Z',
    updatedAt: '2024-12-22T14:00:00Z',
    improvements: ['Include v6 specific parameter updates', 'Add style reference image suggestions'],
    versions: [
      { id: 'v15-1', version: 1, content: 'Create a Midjourney prompt for this concept.', createdAt: '2024-06-15T11:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v15-2', version: 2, content: 'Optimized Midjourney prompt with parameters, 3 variations, and negative prompts.', createdAt: '2024-12-22T14:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p16',
    title: 'Code Review Assistant',
    description: 'Performs thorough code reviews with security, performance, and style checks.',
    content: 'You are a principal engineer conducting a code review. Review the provided code for: 1) Correctness — logic errors, edge cases, off-by-one errors. 2) Security — injection risks, auth issues, data exposure. 3) Performance — time/space complexity, unnecessary allocations, N+1 patterns. 4) Maintainability — naming, structure, DRY violations, complexity. 5) Testing — untested paths, suggested test cases. Rate severity of each finding (critical/major/minor/suggestion). Format as a PR review with inline code references.',
    category: 'Coding',
    models: ['Claude', 'GPT-4', 'GPT-4o'],
    bestModel: 'Claude',
    tags: ['code-review', 'security', 'best-practices', 'quality'],
    effectiveness: 5,
    qualityTag: 'great',
    usageCount: 167,
    project: 'E-commerce Platform',
    isFavorite: true,
    createdAt: '2024-05-20T08:00:00Z',
    updatedAt: '2025-02-10T11:00:00Z',
    improvements: ['Add language-specific linting rule references', 'Include auto-fix suggestions where possible'],
    versions: [
      { id: 'v16-1', version: 1, content: 'Review this code for bugs and improvements.', createdAt: '2024-05-20T08:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v16-2', version: 2, content: 'Review for correctness, security, performance, maintainability, and testing. Rate severity of findings.', createdAt: '2024-10-01T09:00:00Z', rating: 4, qualityTag: 'great' },
      { id: 'v16-3', version: 3, content: 'Full principal-engineer code review with severity ratings, inline references, and testing suggestions.', createdAt: '2025-02-10T11:00:00Z', rating: 5, qualityTag: 'great' },
    ],
  },
  {
    id: 'p17',
    title: 'Email Copywriter',
    description: 'Writes conversion-focused email sequences with A/B test variations.',
    content: 'You are a direct-response email copywriter. Write an email for the specified campaign goal (welcome, nurture, conversion, re-engagement, or announcement). Include: attention-grabbing subject line (+ 2 A/B variations), preview text, personalized greeting, body copy using PAS or AIDA framework, clear CTA button text, and P.S. line. Keep under 200 words for the body. Tone should match the brand voice described. Include send timing recommendation.',
    category: 'Writing',
    models: ['GPT-4o', 'Claude'],
    bestModel: 'GPT-4o',
    tags: ['email', 'copywriting', 'marketing', 'conversion'],
    effectiveness: 3,
    qualityTag: 'okay',
    usageCount: 48,
    project: 'E-commerce Platform',
    isFavorite: false,
    createdAt: '2024-11-10T09:00:00Z',
    updatedAt: '2025-01-08T14:00:00Z',
    improvements: ['Add segmentation criteria guidance', 'Include mobile preview considerations', 'Specify compliance requirements (CAN-SPAM, GDPR)'],
    versions: [
      { id: 'v17-1', version: 1, content: 'Write a marketing email for this campaign.', createdAt: '2024-11-10T09:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v17-2', version: 2, content: 'Write email with subject line variations, PAS framework, CTA, and send timing. Under 200 words.', createdAt: '2025-01-08T14:00:00Z', rating: 3, qualityTag: 'okay' },
    ],
  },
  {
    id: 'p18',
    title: 'Financial Data Analyst',
    description: 'Interprets financial data with trend analysis and actionable insights.',
    content: 'You are a CFA-certified financial analyst. Analyze the provided financial data and deliver: 1) Key Metrics Summary — revenue, margins, growth rates, ratios. 2) Trend Analysis — identify patterns over the time period with specific numbers. 3) Peer Comparison — benchmark against industry averages. 4) Risk Indicators — flag concerning metrics with explanations. 5) Actionable Insights — 3-5 specific recommendations with expected financial impact. Present data in a clean tabular format where applicable. Use precise financial terminology.',
    category: 'Analysis',
    models: ['GPT-4', 'Claude', 'Gemini Pro'],
    bestModel: 'GPT-4',
    tags: ['finance', 'data-analysis', 'reporting', 'metrics'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 52,
    project: undefined,
    isFavorite: false,
    createdAt: '2024-08-28T15:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
    improvements: ['Specify fiscal year convention', 'Add currency and GAAP/IFRS context'],
    versions: [
      { id: 'v18-1', version: 1, content: 'Analyze this financial data and provide insights.', createdAt: '2024-08-28T15:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v18-2', version: 2, content: 'Full financial analysis with metrics, trends, peer comparison, risk indicators, and recommendations.', createdAt: '2024-12-15T10:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p19',
    title: 'Product Naming Generator',
    description: 'Creates memorable product names with domain availability heuristics.',
    content: 'You are a brand naming specialist. Generate 15 product name candidates for the described product/service. For each name provide: the name itself, pronunciation guide (if non-obvious), meaning/origin, emotional associations, potential domain (.com/.io/.co availability estimate), and trademark risk level (low/medium/high). Organize into categories: descriptive, evocative, invented, and acronym-based. Rank your top 5 with reasoning. Names should be: 1-3 syllables, easy to spell, memorable, and culturally appropriate for global markets.',
    category: 'Brainstorming',
    models: ['Gemini Pro', 'GPT-4o', 'Claude'],
    bestModel: 'Gemini Pro',
    tags: ['branding', 'naming', 'creative', 'product'],
    effectiveness: 3,
    qualityTag: 'okay',
    usageCount: 29,
    project: 'Mobile App',
    isFavorite: false,
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2025-01-18T09:00:00Z',
    improvements: ['Add competitor name landscape analysis', 'Include visual/logo direction suggestions per name'],
    versions: [
      { id: 'v19-1', version: 1, content: 'Come up with 15 product name ideas.', createdAt: '2024-12-01T10:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v19-2', version: 2, content: 'Generate 15 names with pronunciations, meanings, domain estimates, and trademark risk. Rank top 5.', createdAt: '2025-01-18T09:00:00Z', rating: 3, qualityTag: 'okay' },
    ],
  },
  {
    id: 'p20',
    title: 'TypeScript Type Generator',
    description: 'Creates precise TypeScript types from API responses or data samples.',
    content: 'You are a TypeScript expert. Generate precise TypeScript type definitions from the provided data sample or API response. Use: interfaces for object shapes, union types for constrained values, utility types where appropriate (Partial, Pick, Omit, Record), branded types for IDs and special strings, and generic types for reusable patterns. Add JSDoc comments explaining each type. If the data suggests an API, generate both request and response types. Include a type guard function for runtime validation.',
    category: 'Coding',
    models: ['Claude', 'GPT-4'],
    bestModel: 'Claude',
    tags: ['typescript', 'types', 'api', 'code-generation'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 98,
    project: 'E-commerce Platform',
    isFavorite: false,
    createdAt: '2024-07-30T12:00:00Z',
    updatedAt: '2025-01-22T08:00:00Z',
    improvements: ['Add Zod schema generation option', 'Include JSON Schema to TypeScript conversion'],
    versions: [
      { id: 'v20-1', version: 1, content: 'Generate TypeScript types from this data.', createdAt: '2024-07-30T12:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v20-2', version: 2, content: 'Generate precise TS types with interfaces, unions, utility types, branded types, JSDoc, and type guards.', createdAt: '2025-01-22T08:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p21',
    title: 'Legal Document Simplifier',
    description: 'Translates complex legal language into plain, understandable English.',
    content: 'You are a legal communication specialist. Rewrite the provided legal document or clause in plain English that a non-lawyer can understand. Maintain legal accuracy while eliminating jargon. For each section provide: a) Plain English version. b) "What this means for you" summary in one sentence. c) Key obligations or rights highlighted. d) Red flags or unusual clauses flagged. Do NOT provide legal advice—clearly state this is for comprehension purposes only. Preserve section numbering for reference.',
    category: 'Translation',
    models: ['GPT-4', 'Claude'],
    bestModel: 'GPT-4',
    tags: ['legal', 'plain-language', 'contracts', 'simplification'],
    effectiveness: 3,
    qualityTag: 'okay',
    usageCount: 27,
    project: undefined,
    isFavorite: false,
    createdAt: '2024-10-05T11:00:00Z',
    updatedAt: '2024-12-18T16:00:00Z',
    improvements: ['Add jurisdiction context', 'Include common negotiation points per clause type'],
    versions: [
      { id: 'v21-1', version: 1, content: 'Simplify this legal document into plain English.', createdAt: '2024-10-05T11:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v21-2', version: 2, content: 'Rewrite in plain English with "what this means" summaries, key obligations, and red flags.', createdAt: '2024-12-18T16:00:00Z', rating: 3, qualityTag: 'okay' },
    ],
  },
  {
    id: 'p22',
    title: 'Error Log Analyzer',
    description: 'Parses application logs to identify patterns, root causes, and fixes.',
    content: 'You are a DevOps/SRE engineer. Analyze the provided application error logs and produce: 1) Error Classification — group errors by type and frequency. 2) Root Cause Analysis — identify the most likely root cause for each error cluster. 3) Timeline Reconstruction — map error patterns to events or deployments. 4) Impact Assessment — estimate user-facing impact and affected services. 5) Remediation Plan — prioritized fix recommendations with estimated effort. Highlight any correlation between error spikes and deployments or external dependencies.',
    category: 'Debugging',
    models: ['Llama 3', 'Claude', 'GPT-4'],
    bestModel: 'Llama 3',
    tags: ['devops', 'logs', 'monitoring', 'incident-response'],
    effectiveness: 3,
    qualityTag: 'okay',
    usageCount: 41,
    project: 'Data Pipeline',
    isFavorite: false,
    createdAt: '2024-09-20T13:00:00Z',
    updatedAt: '2025-01-05T15:00:00Z',
    improvements: ['Specify log format (JSON/syslog/custom)', 'Add alerting threshold recommendations'],
    versions: [
      { id: 'v22-1', version: 1, content: 'Analyze these error logs and tell me what\'s wrong.', createdAt: '2024-09-20T13:00:00Z', rating: 2, qualityTag: 'poor' },
      { id: 'v22-2', version: 2, content: 'Classify errors, analyze root causes, reconstruct timeline, assess impact, and provide remediation plan.', createdAt: '2025-01-05T15:00:00Z', rating: 3, qualityTag: 'okay' },
    ],
  },
  {
    id: 'p23',
    title: 'Academic Paper Summarizer',
    description: 'Creates structured summaries of academic papers for quick review.',
    content: 'Summarize the following academic paper for a graduate-level audience. Provide: Abstract rewrite (3 sentences), research question and hypothesis, methodology overview with sample size and design, key findings with specific statistical results, theoretical and practical implications, study limitations and future research directions, and 5 key terms defined. Rate the paper\'s overall rigor on a 1-10 scale with brief justification.',
    category: 'Summarization',
    models: ['Claude', 'GPT-4o'],
    bestModel: 'Claude',
    tags: ['academic', 'summarization', 'research', 'education'],
    effectiveness: 5,
    qualityTag: 'great',
    usageCount: 89,
    project: undefined,
    isFavorite: true,
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2025-02-08T12:00:00Z',
    improvements: ['Add field-specific context (CS, medicine, social science)', 'Include methodology critique section'],
    versions: [
      { id: 'v23-1', version: 1, content: 'Summarize this academic paper.', createdAt: '2024-06-01T09:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v23-2', version: 2, content: 'Structured summary with methodology, findings, implications, limitations, and rigor rating.', createdAt: '2025-02-08T12:00:00Z', rating: 5, qualityTag: 'great' },
    ],
  },
  {
    id: 'p24',
    title: 'Test Case Generator',
    description: 'Creates comprehensive test suites from function signatures and requirements.',
    content: 'You are a QA engineer writing a test suite. From the provided function signature, implementation, and requirements, generate comprehensive test cases. Include: happy path tests, edge cases (empty inputs, nulls, boundary values, overflow), error handling tests, integration test scenarios if applicable, and performance considerations. Format as executable test code using the specified framework (Jest/Vitest/pytest). Each test should have a descriptive name explaining what it verifies. Aim for >90% code coverage.',
    category: 'Coding',
    models: ['GPT-4o', 'Claude'],
    bestModel: 'GPT-4o',
    tags: ['testing', 'qa', 'jest', 'test-automation'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 76,
    project: 'E-commerce Platform',
    isFavorite: false,
    createdAt: '2024-08-05T14:00:00Z',
    updatedAt: '2025-01-28T10:00:00Z',
    improvements: ['Add mutation testing suggestions', 'Include test data factory patterns'],
    versions: [
      { id: 'v24-1', version: 1, content: 'Write tests for this function.', createdAt: '2024-08-05T14:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v24-2', version: 2, content: 'Comprehensive test suite with happy path, edge cases, error handling, and >90% coverage target.', createdAt: '2025-01-28T10:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
  {
    id: 'p25',
    title: 'Content Calendar Planner',
    description: 'Creates strategic content calendars with topics, formats, and distribution plans.',
    content: 'You are a content marketing manager. Create a 4-week content calendar for the specified brand/product. For each piece of content include: publish date, content type (blog, video, social post, newsletter, podcast), topic/headline, target keyword, target audience segment, distribution channels, content pillar it supports, estimated production time, and KPIs to track. Include a mix of evergreen and trending content. Ensure balanced coverage across all audience segments and content pillars. Suggest 2 content repurposing opportunities per week.',
    category: 'Writing',
    models: ['Gemini Pro', 'GPT-4o', 'Claude'],
    bestModel: 'Gemini Pro',
    tags: ['content-strategy', 'marketing', 'planning', 'calendar'],
    effectiveness: 4,
    qualityTag: 'great',
    usageCount: 33,
    project: 'Blog Engine',
    isFavorite: false,
    createdAt: '2024-11-18T10:00:00Z',
    updatedAt: '2025-01-25T16:00:00Z',
    improvements: ['Add seasonal/holiday content hooks', 'Include competitor content gap analysis'],
    versions: [
      { id: 'v25-1', version: 1, content: 'Create a content calendar for 4 weeks.', createdAt: '2024-11-18T10:00:00Z', rating: 3, qualityTag: 'okay' },
      { id: 'v25-2', version: 2, content: '4-week calendar with content types, keywords, audiences, channels, pillars, and repurposing opportunities.', createdAt: '2025-01-25T16:00:00Z', rating: 4, qualityTag: 'great' },
    ],
  },
];

export const ALL_CATEGORIES: string[] = [
  'Coding', 'Writing', 'Analysis', 'Brainstorming',
  'Data Extraction', 'Image Generation', 'Translation',
  'Debugging', 'Summarization', 'Research',
];

export const ALL_MODELS: string[] = [
  'Claude', 'GPT-4', 'GPT-4o', 'Gemini Pro', 'Llama 3', 'Mistral',
];

export const ALL_PROJECTS: string[] = [
  'E-commerce Platform', 'Blog Engine', 'Data Pipeline', 'Mobile App', 'AI Assistant',
];
